[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf_shared = "0.11.1"
phf_generator = "0.11.1"
const_format = "0.2.30"
ureq = "2.6.2"
